Cleanup: Remove .env from tracking and update .gitignore
D:\Ani\College\2nd Year\sem 4\Database Information Systems\ALSBookingsLive>git push origin main
To https://github.com/Anirudh-San/ALSBookings
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/Anirudh-San/ALSBookings'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.#